const listaQuestoes=document.getElementById('lista-questoes');
async function carregarQuestoes(){limparElemento(listaQuestoes);try{const itens=await explainerRequest('/questoes');if(!itens.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=4;td.textContent='Nenhuma questão cadastrada.';tr.appendChild(td);listaQuestoes.appendChild(tr);return;}itens.forEach(q=>{const tr=document.createElement('tr');[q.id_questao,q.enunciado,q.alternativa_correta,q.id_tema].forEach(v=>adicionarCelula(tr,v));listaQuestoes.appendChild(tr);});}catch(e){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=4;td.textContent=e.message;tr.appendChild(td);listaQuestoes.appendChild(tr);}}

document.getElementById('form-questao')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-questao');const dados=Object.fromEntries(new FormData(event.currentTarget));dados.id_tema=Number(dados.id_tema);dados.alternativa_correta=dados.alternativa_correta.trim().toUpperCase()||null;try{await explainerRequest('/questoes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dados)});mostrarMensagem(msg,'Questão cadastrada com sucesso.');event.currentTarget.reset();carregarQuestoes();}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.getElementById('form-verificar')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-verificar');const id=document.getElementById('questao-id-verificar').value;const alternativa=document.getElementById('questao-alternativa-verificar').value.trim().toUpperCase();try{const resultado=await explainerRequest(`/questoes/${id}/verificar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({alternativa})});mostrarMensagem(msg,resultado.correta?'Resposta correta.':'Resposta incorreta.',resultado.correta?'sucesso':'aviso');}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.getElementById('form-questao-atualizar')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-questao-atualizar');const id=document.getElementById('questao-id-atualizar').value;const dados={};const enunciado=document.getElementById('questao-enunciado-atualizar').value.trim();const alternativa=document.getElementById('questao-alternativa-atualizar').value.trim().toUpperCase();const tema=document.getElementById('questao-tema-atualizar').value;if(enunciado)dados.enunciado=enunciado;if(alternativa)dados.alternativa_correta=alternativa;if(tema)dados.id_tema=Number(tema);if(!Object.keys(dados).length)return mostrarMensagem(msg,'Preencha pelo menos um campo.','aviso');try{await explainerRequest(`/questoes/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(dados)});mostrarMensagem(msg,'Questão atualizada com sucesso.');event.currentTarget.reset();carregarQuestoes();}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.getElementById('form-questao-deletar')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-questao-deletar');const id=document.getElementById('questao-id-deletar').value;if(!confirm(`Excluir a questão ${id}?`))return;try{await explainerRequest(`/questoes/${id}`,{method:'DELETE'});mostrarMensagem(msg,'Questão excluída com sucesso.');event.currentTarget.reset();carregarQuestoes();}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.addEventListener('DOMContentLoaded',carregarQuestoes);
