const listaRanking=document.getElementById('lista-ranking');const listaRankingAlunos=document.getElementById('lista-ranking-alunos');

async function carregarRanking(){limparElemento(listaRanking);try{const itens=await explainerRequest('/ranking');if(!itens.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=4;td.textContent='Nenhum registro de ranking.';tr.appendChild(td);listaRanking.appendChild(tr);}else{itens.forEach(item=>{const tr=document.createElement('tr');[item.id_ranking,item.classificacao,item.pontos,item.id_aluno].forEach(v=>adicionarCelula(tr,v));listaRanking.appendChild(tr);});}}catch(e){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=4;td.textContent=e.message;tr.appendChild(td);listaRanking.appendChild(tr);}}

async function carregarRankingAlunos(){limparElemento(listaRankingAlunos);try{const itens=await explainerRequest('/alunos/ranking');if(!itens.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=3;td.textContent='Ainda não há classificação disponível.';tr.appendChild(td);listaRankingAlunos.appendChild(tr);}else{itens.forEach(item=>{const tr=document.createElement('tr');[item.classificacao,item.nome,item.pontos].forEach(v=>adicionarCelula(tr,v));listaRankingAlunos.appendChild(tr);});}}catch(e){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=3;td.textContent=e.message;tr.appendChild(td);listaRankingAlunos.appendChild(tr);}}

function recarregar(){carregarRanking();carregarRankingAlunos();}

document.getElementById('form-ranking')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-ranking');const dados=Object.fromEntries(new FormData(event.currentTarget));dados.classificacao=Number(dados.classificacao);dados.pontos=Number(dados.pontos);dados.id_aluno=Number(dados.id_aluno);try{await explainerRequest('/ranking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(dados)});mostrarMensagem(msg,'Registro de ranking criado.');event.currentTarget.reset();recarregar();}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.getElementById('form-ranking-atualizar')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-ranking-atualizar');const id=document.getElementById('ranking-id-atualizar').value;const dados={};const classificacao=document.getElementById('ranking-classificacao-atualizar').value;const pontos=document.getElementById('ranking-pontos-atualizar').value;const aluno=document.getElementById('ranking-aluno-atualizar').value;if(classificacao)dados.classificacao=Number(classificacao);if(pontos)dados.pontos=Number(pontos);if(aluno)dados.id_aluno=Number(aluno);if(!Object.keys(dados).length)return mostrarMensagem(msg,'Preencha pelo menos um campo.','aviso');try{await explainerRequest(`/ranking/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(dados)});mostrarMensagem(msg,'Ranking atualizado.');event.currentTarget.reset();recarregar();}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.getElementById('form-ranking-deletar')?.addEventListener('submit',async event=>{event.preventDefault();const msg=document.getElementById('mensagem-ranking-deletar');const id=document.getElementById('ranking-id-deletar').value;if(!confirm(`Excluir o ranking ${id}?`))return;try{await explainerRequest(`/ranking/${id}`,{method:'DELETE'});mostrarMensagem(msg,'Ranking excluído.');event.currentTarget.reset();recarregar();}catch(e){mostrarMensagem(msg,e.message,'erro');}});

document.addEventListener('DOMContentLoaded',recarregar);
